# Generated by Django 6.0.1 on 2026-06-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('submitted', 'Отправлено'), ('checked', 'Проверено')], default='in_progress', max_length=50)),
                ('time_spent_minutes', models.IntegerField(blank=True, null=True)),
                ('max_earned_points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Прогресс задания',
                'verbose_name_plural': 'Прогрессы заданий',
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.IntegerField(blank=True, null=True)),
                ('ai_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Результат проверки',
                'verbose_name_plural': 'Результаты проверок',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='StepAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('submitted', 'Отправлено'), ('checked', 'Проверено')], default='in_progress', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Попытка шага',
                'verbose_name_plural': 'Попытки шагов',
            },
        ),
    ]
